import os
import glob

figure_dir = 'figures'
artifact_dir = r'C:\Users\athar\.gemini\antigravity-ide\brain\d5e1e49c-89e5-42a7-9d5f-9a3c86ccddd3'
guide_path = os.path.join(artifact_dir, 'figure_generation_guide.md')

all_pngs = sorted(glob.glob(os.path.join(figure_dir, '*.png')))

# Copy all images to artifact dir (skip if already exists to save time, or just copy all)
import shutil
for png in all_pngs:
    dest = os.path.join(artifact_dir, os.path.basename(png))
    shutil.copy(png, dest)

with open(guide_path, 'a', encoding='utf-8') as f:
    f.write('\n\n---\n## Comprehensive Archive (All Generated Diagrams)\n\n')
    f.write('The following is an exhaustive archive of all generated diagrams found in the repository, grouped by their origin. Their equations rely on the baseline probabilistic and latency models established earlier.\n\n')
    
    for png in all_pngs:
        basename = os.path.basename(png)
        # Skip the ones we already covered manually
        if basename in ['fig_1_architecture.png', 'fig_2_protocol_flow.png', 'fig_3_probability_tree.png', 
                        'fig_4_radar_comparison.png', 'fig_5_poisson_timeline.png', 'fig_6_spof_risk.png', 
                        'fig_7_eta_sensitivity.png', 'fig_8_blockchain_arch.png', 'fig_9_attack_graph.png', 
                        'fig_10_methodology_pipeline.png', 'fig_ptemporal_vs_latency.png', 
                        'fig_robustness_heatmap.png', 'fig_pareto_frontier.png', 'fig_attack_rate_heatmap.png']:
            continue
            
        desc = "Generated by the comparative simulation framework."
        eq = "Relies on comparative latency and throughput empirical models."
        if basename.startswith('analytical_'):
            desc = "Generated by probabilistic_model.py focusing on analytical system limits."
            eq = "P_{Byz} = \sum_{i=f+1}^{n} \binom{n}{i} p_c^i (1-p_c)^{n-i} and L_{total} = L_{net} + L_{consensus}"
        elif basename.startswith('comparison_'):
            desc = "Generated by benchmarking scripts highlighting relative performance."
            eq = "Empirical plotting of {secure}$ versus throughput/latency metrics."
        elif basename.startswith('fig_w2_'):
            desc = "Generated by generate_week2_figures.py detailing energy and probabilistic variations."
            eq = "Energy modeled as {total} = E_{tx} + E_{rx} + E_{crypto}$."
        elif basename.startswith('fig1') or basename.startswith('fig2') or basename.startswith('fig3') or basename.startswith('fig4') or basename.startswith('fig5') or basename.startswith('fig6') or basename.startswith('fig7') or basename.startswith('fig8') or basename.startswith('fig9'):
            desc = "Generated by legacy generate_new_figures.py representing specific thesis chapter results."
            eq = "Temporal vulnerability: {temporal} = 1 - e^{-\lambda L P_{TA}}$"
        elif basename.startswith('fig_'):
            desc = "Generated by generate_ieee_figures.py showing sensitivity matrices and distributions."
            eq = "Multivariate correlation: {fail} = \min(1, P_{static} + P_{temporal} - \\rho \min(P_{static}, P_{temporal}))$"

        f.write(f'### {basename}\n')
        f.write(f'![{basename}](file:///{artifact_dir}/{basename})\n\n')
        f.write(f'* **Concept/Origin:** {desc}\n')
        f.write(f'* **Equations/Framework:** {eq}\n')
        f.write('---\n\n')

print("Exhaustive guide updated successfully!")
